name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

  deploy:
  needs: test
  runs-on: self-hosted
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download test artifact
      uses: actions/download-artifact@v3
      with:
        name: test-results
        path: ./test-results

    - name: Show test results
      run: cat ./test-results/results.txt

    - name: Deploy app
      shell: pwsh
      run: ./deploy.ps2
